### ISSUE TITLE
AttributeError on add_discourse_resource

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/measure#56]
```
measure.datastore_get_latest: INFO    :Processed 1 rows
measure.add_discourse_resource: /usr/local/lib/python3.6/site-packages/jsontableschema/model.py:48: UserWarning: Class models.SchemaModel is deprecated [v0.7-v1)
measure.add_discourse_resource:   warnings.warn(message, UserWarning)
measure.add_discourse_resource: DEBUG   :Starting new HTTPS connection (1): discuss.okfn.org
measure.add_discourse_resource: DEBUG   :https://discuss.okfn.org:443 "GET /admin/users/list/active.json?api_key=<API_KEY>&page=1 HTTP/1.1" 200 None
measure.add_discourse_resource: Traceback (most recent call last):
measure.add_discourse_resource:   File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines_measure/processors/add_discourse_resource.py", line 134, in 
measure.add_discourse_resource:     spew(datapackage, process_resources(res_iter, datapackage, domain))
measure.add_discourse_resource:   File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/wrapper/wrapper.py", line 55, in spew
measure.add_discourse_resource:     for res in resources_iterator:
measure.add_discourse_resource:   File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines_measure/processors/add_discourse_resource.py", line 131, in process_resources
measure.add_discourse_resource:     yield discourse_collector(domain, latest_row)
measure.add_discourse_resource:   File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines_measure/processors/add_discourse_resource.py", line 45, in discourse_collector
measure.add_discourse_resource:     active_users_response = _get_active_users_number_last_24_hrs(domain)
measure.add_discourse_resource:   File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines_measure/processors/add_discourse_resource.py", line 39, in _get_active_users_number_last_24_hrs
measure.add_discourse_resource:     return len(list(_page_active_users(domain)))
measure.add_discourse_resource:   File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines_measure/processors/add_discourse_resource.py", line 35, in _page_active_users
measure.add_discourse_resource:     if not user['last_seen_age'].endswith(('h', 'm')):
measure.add_discourse_resource: AttributeError: 'float' object has no attribute 'endswith'
measure.remove_resource: /usr/local/lib/python3.6/site-packages/jsontableschema/model.py:48: UserWarning: Class models.SchemaModel is deprecated [v0.7-v1)
measure.remove_resource:   warnings.warn(message, UserWarning)
```

**Comment by brew** [comment]
Fixed by 2370dd5445aa214cc8040a263e3b42f6eed78815
